project_name: disco

env:
- GO111MODULE=on

before:
  hooks:
  - go mod tidy

gomod:
  proxy: false

sboms:
- artifacts: binary

builds:
- binary: disco
  mod_timestamp: '{{ .CommitTimestamp }}'
  dir: ./cmd/cli
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w -X main.version={{.Version}}
  - -s -w -X main.commit={{.ShortCommit}}
  - -s -w -X main.date={{.Date}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: mchmarny
    name: disco
  prerelease: auto

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - readme
    - typo
    - "version bump"

brews:
- tap:
    owner: mchmarny
    name: homebrew-disco
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: "https://github.com/mchmarny/disco"
  description: "Utility for bulk image, license, and vulnerability discovery in containerize workloads on GCP."
  folder: Formula
  license: "Apache-2.0"
  test: |
    system "#{bin}/disco --version"

nfpms:
- file_name_template: "disco-{{.Version}}_{{.Os}}-{{.Arch}}"
  homepage: https://github.com/mchmarny/disco/
  description: "Utility for bulk image, license, and vulnerability discovery in containerize workloads on GCP."
  maintainer: disco developers <disco@chmarny.com>
  license: Apache 2.0
  vendor: disco developers
  formats:
  - deb
  - rpm
  bindir: /usr/bin

universal_binaries:
- replace: true
  name_template: 'disco'
