#!/bin/bash

set -o errexit

# projects 
curl -Ss -H "Content-Type: application/json; charset=utf-8" \
     -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
     "https://cloudresourcemanager.googleapis.com/v1/projects" | \
     jq -r '.projects[] | select(.parent.type == "organization") | select(.lifecycleState == "ACTIVE") | .projectNumber'

# does project has cloud run anabled? 
curl -Ss -H "Content-Type: application/json; charset=utf-8" \
     -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://serviceusage.googleapis.com/v1/projects/799736955886/services?filter=state:ENABLED" | \
    jq -r '.services[] | select(.config.name == "run.googleapis.com") | .config.name'
    
# list of regions where run is supported
curl -Ss -H "Content-Type: application/json; charset=utf-8" \
     -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://run.googleapis.com/v1/projects/799736955886/locations" | \
    jq -r '.locations[] | .locationId'

# list all services in this region for this project
curl -Ss -H "Content-Type: application/json; charset=utf-8" \
     -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://run.googleapis.com/v1/projects/799736955886/locations/us-west1/services" | \
    jq -r '.items[] | .metadata.name'

# get the service image uri

curl -Ss -H "Content-Type: application/json; charset=utf-8" \
     -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://run.googleapis.com/v1/projects/799736955886/locations/us-west1/services/artomator"




# get revisions 
curl -Ss -H "Content-Type: application/json; charset=utf-8" \
     -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://run.googleapis.com/v2/projects/cloudy-demos/locations/us-west1/services/artomator/revisions/artomator-qx5lj"


curl -Ss -H "Content-Type: application/json; charset=utf-8" \
     -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://run.googleapis.com/v1/projects/799736955886/locations/us-west1/services/artomator" | \
    jq -r '.spec.template.spec.containers[0].image'


# get the digest from manifest
curl -i -H HEAD -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://us-west1-docker.pkg.dev/v2/cloudy-demos/artomator/artomator/manifests/v0.8.3"

    
# artifact registry get digest
curl -Ss -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://us-west1-docker.pkg.dev/v2/cloudy-demos/artomator/artomator/manifests/v0.8.3" | \
     jq -r '.config.digest'

curl -Ss -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://us-docker.pkg.dev/v2/cloudrun/container/hello/manifests/latest"
    

# gcr 
curl -Ss -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://gcr.io/v2/cloudy-demos/hello-broken/manifests/latest" | \
     jq -r '.config.digest'


# kind="PACKAGE" AND noteProjectId="cloudy-demos"

# export FILTER="resourceUrl%3D%22https%3A%2F%2Fgcr.io%2Fcloudy-demos%2Fhello-broken%40sha256%3A0900c08e7d40f9485c8497c035de07391ba3c274a1035f504f8602531b2314e6%22%20AND%20kind%3D%22VULNERABILITY%22"

export FILTER="noteId%3D%22CVE-2017-11164%22"

# kind="PACKAGE"
# noteProjectId="cloudy-demos"
# resourceUrl="projects/PROJECT_ID/locations/LOCATION/repositories/REPOSITORY/mavenArtifacts/PACKAGE_NAME:VERSION"

curl -Ss -H "Content-Type: application/json; charset=utf-8" \
     -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://containeranalysis.googleapis.com/v1/projects/cloudy-demos/occurrences?pageSize=500&filter=resourceUrl%3D%22https%3A%2F%2Fgcr.io%2Fcloudy-demos%2Fhello-broken%40sha256%3A0900c08e7d40f9485c8497c035de07391ba3c274a1035f504f8602531b2314e6%22%20AND%20kind%3D%22VULNERABILITY%22" 

# query 
# resourceUrl="https://gcr.io/cloudy-demos/hello-broken@sha256:e64ed4de03b5f4ee1a8cfb52f5c1aa126ae6a6004657bb7aa490dbf740bd1689" kind="VULNERABILITY"

curl -Ss -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://us-west1-docker.pkg.dev/v2/cloudy-demos/artomator/artomator/tags/list"


# debug double query for digest 
curl -Ss -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
    -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
    "https://us-west1-docker.pkg.dev/v2/cloudy-demos/artomator/artomator/manifests/v0.8.3" | jq -r '.config.digest'

curl -s -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
     -H "Authorization: Bearer $(gcloud auth print-access-token)" \
     "https://us-west1-docker.pkg.dev/v2/cloudy-demos/artomator/artomator/blobs/sha256:d7c0d989fcda512c38cf95c6cb674e5da5f6c08f80589be2938a53c51c230565"


curl -X POST -d \
    '{"version": "2.4.1", "package": {"name": "jinja2", "ecosystem": "PyPI"}}' \
    "https://api.osv.dev/v1/query"