#!/bin/bash

set -e

msg () {
   echo "====== running $1 tests ======"
}

msg "root"
bin/disco -v
bin/disco -h

msg "img"
bin/disco img run --uri -o images.tmp
imgID=$(head -n 1 images.tmp)
echo $imgID

msg "vul"
bin/disco vul --file images.tmp
bin/disco vul --image $imgID
bin/disco vul --file images.tmp --min-severity high
bin/disco vul --file images.tmp --cve CVE-2020-8911
bin/disco vul --file images.tmp --target "bq://cloudy-demos.disco_test.vulnerabilities"

msg "lic"
bin/disco lic
bin/disco lic --file images.tmp
bin/disco lic --image $imgID
bin/disco lic --image $imgID --type MIT
bin/disco lic --file images.tmp --target "bq://cloudy-demos.disco_test.licenses"

msg "pkg"
time bin/disco pkg
time bin/disco pkg --file images.tmp
time bin/disco pkg --image $imgID
time bin/disco pkg --file images.tmp --target "bq://cloudy-demos.disco_test.packages"
